name: Build and Archive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.arch }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.arch }}-

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      env:
        GOARCH: ${{ matrix.arch }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: go build -o bin/${REPO_NAME}-${{ matrix.arch }} ./...

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.arch }}
        path: bin/${{ github.event.repository.name }}-${{ matrix.arch }}

